# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f999f55c85494caa8b04e4e5831aacb8f8f8f33a013477427cd96ed94be989c5340da9d74cce6a824d360fa2be57b386d44e7fa67290565a26e7be1f24c35e4

test:
  secret_key_base: 2ab5e51e2acc3e1a7ab64fa54308e084a17692553be2564e775da921cb6fc9e6ec7f6415b81462f8a3a4434d693c3e9fa36b42b21498ce17466e3aa646a675cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
